version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rnfma!234"
      MYSQL_DATABASE: "cloudDB"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
