  version: "3.8"

  services:
    mysql:
      image: mysql:latest
      container_name: mysql-container
      ports:
        - "3305:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "rnfma!234"
      restart: unless-stopped
